version: "2"
services:
  app:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/webchat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8080"
#    network_mode: host
#    links:
#      - db
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=webchat
volumes:
  postgres_data: